### ISSUE TITLE
What are you doing that requires SDK 21?

### ISSUE THREAD

**Issue by Ilya-Gazman** [Tibolte/ElasticDownload#20]
How about making it 8?

Please ;)

**Comment by Tibolte** [comment]
This was intended at the beginning, turned out I had to use AnimatedVectorDrawable (https://developer.android.com/reference/android/graphics/drawable/AnimatedVectorDrawable.html) introduced in API level 21, in order to perform the intro (arrow morphing into bubble with percentage).

Actually VectorDrawableCompat are coming soon to Android (or yet?): https://android.googlesource.com/platform/frameworks/support/+/master/v7/vectordrawable/
But not sure if AnimatedVectorDrawable are gonna be provided with this.

Last resort is to use a third-party library that enables this: https://github.com/wnafee/vector-compat
I haven't tested it yet.

This is definitely possible, but choice has to be made wisely :)

**Comment by Ilya-Gazman** [comment]
I may have an incentive that can help you proving "This is definitely possible". 

I got  100K people app that is currently unpublished on google play and I am about to republish it next week. Do this and not only that I will use your library I will also share you repo(or another related link if you will) in a very visible place in the app, but it have to be available in API 9.

I am saying "very"  as the main purpose of the app is to publish my own SDK  
https://github.com/Ilya-Gazman/android_life_cycle

So I hope you be able to make it, cheers!

**Comment by Tibolte** [comment]
Sounds awesome! I'm definitely interested in supporting for API level 9, I'll give it a try and notify you here!

**Comment by Tibolte** [comment]
I managed to backport to API 8 actually, I have a device with API 10 and it works well so far. Couldn't get a hand on API 8 for now, but I believe this should be OK. It will be available in release 1.0.3 soon!
